In [4]:
import numpy as np
np.version.version

'1.19.2'

In [15]:
arr=np.array([3,5,6,7])
type(arr)
arr.dtype
arr.ndim
arr.size
arr.shape
arr

array([3, 5, 6, 7])

In [28]:
arr=np.array([['r','e','d'],
             [5,6,7]])
arr
type(arr)
arr.size
arr.shape
arr.ndim
arr.dtype

dtype('<U1')

In [32]:
arr=np.zeros((2,3,3))
arr

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
arr=np.array([[[1,2,3],
              [4,5,6]],
             
             [[7,8,9],
             [3,7,0]],
              
              [[1,1,2],
              [6,7,8]],
             
             [[3,4,5],
             [7,8,8]]])
arr
arr.ndim
arr.size
type(arr)
arr.dtype
arr.shape

(4, 2, 3)

In [40]:
arr=np.ones((2,3,4))
arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [43]:
cons=np.full((2,2),4)
cons
cons[0][0]=3
cons

array([[3, 4],
       [4, 4]])

In [44]:
iden=np.eye(3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
rand_arr=np.random.random((3,3))
rand_arr

array([[0.3562842 , 0.28400126, 0.27215427],
       [0.70521118, 0.47445832, 0.08965778],
       [0.76659876, 0.38837202, 0.42407824]])